### PR TITLE
Two new dishes; clone of MT3 profile; second HiPro clone with more accurate dishes

### PR DESCRIPTION
**Pull request by mrebersv**
Adding new dishes, a profile clone of MT3 (Matty3...not sure about copyrights on the MT3 name, at the moment), and a second HiPro clone with more accurate dishes.

### CODE REVIEW

**Comment by mrebersv** [comment]
This replaces my pull request from earlier.  Fixed the scoops so they work properly with all keycap sizes.

**Review by rsheldiii — COMMENTED** [review]
I like these changes a lot!

I was unaware there were "hipro" keycaps coming out, I figured they were more of a family of styles. `hipro_row` was my version of your matty3 profile, with measurements I took from some mt3 caps myself. I think we should just get rid of the original `hipro_row` and rename `hipro2_row` to `hipro_row`.

Thinking about it now, If we were to have IP issues on the mt3 name, we'd have IP issues on DCS and DSA as well, so we might as well just call it what it is, rename `matty3_row` to `mt3_row`. I can get in touch with matt3o about it but I've been reticent to poke the bear around intellectual property since some laws require defending them - so the answer might just be 'no' because a 'yes' in writing forfeits some amount of rights. I don't really think this library is competition for actual keyset makers anyways.

The `squared_scoop` dish digs into the sides of the cap because the width / height passed through is the maximum bounds of the keytop - any rounding done by `sculpted_square` will be inside those bounds. Instead of trying to reverse engineer the  keytop shape, if you just replace `cube([height,width,0.001],center=true);` with `translate([0,0,-$total_depth])shape_slice(1,0,0);` it should work with any key shape, and hugs the sides:

image

Once the above change and the renaming + deleting the original `hipro` is done we can merge this!

**Comment by mrebersv** [comment]
This is great Info! And I was about to rescind this pull request anyway.
Working with another member to truly mail down mt3 specs and going to
incorporate those. I’ll also do your requirements as well

Side note: I’m not sure the sculpted square is right for hippo, but it
definitely isn’t spherical (normal). Sperhical square may be correct.

**Comment by mrebersv** [comment]
For `squared_scoop`, I replaced the code I had with the code you suggested.  Unfortunately, I'm getting an issue best illustrated by the screenshot attached (full render, though happens in the preview as well).  Any idea what's going on here and how to resolve?
cap problem

**Comment by rsheldiii** [comment]
hm. `shape_slice(1,0,0);` is exactly the shape at the top of the key, so I'm not sure. It almost looks like the top tilt is off a bit. what is the code that's generating that keycap?

**Comment by mrebersv** [comment]
From my fork (https://github.com/mrebersv/KeyV2), but with your change from above in `squared_scoop`:

```
include <./includes.scad>

hipro2_row() key();
```

**Comment by mrebersv** [comment]
FYI, HiPro keycaps **_might_** have a dish more similar to `squared_spherical` than `squared_scoop`.  I've never seen HiPro caps in person, and only looked at a few pics that, to me, looked like squared_scoop.  Even if HiPro keycaps are `squared_spherical`, I think having the additional dish would still be a good addition to your awesome repo, though.  Especially since I plan on trying that scoop out when my 3d printer ships ;-)

Of course, I could always just use my fork for that type of keycap design.  

Also, the renaming of things will happen after @jwhendy and I have more finely tuned the mt3 clone.

**Comment by toniz4** [comment]
Now there is a publicly avalible mt3 stl, by the man himself https://matt3o.com/mt3-stl-files-for-artisan-keycap-designers/

It is for artisan keycap designers, but I think if the credit is given it would not be a problem, since is based on the Attribution-ShareAlike licence. 

It has only a row 0 keycap and a spacebar keycap, but it shoud be enouth for reference.

Something that I noticed is that the original mt3 has something like a lip at the edges, before the dish cutout. This feature is kinda present in the sqared scoop dish.

I wish I knew more about scad to contribute for this, but now this is the maximum I can do. I'm taking a close look at this PR, I plan to mjf print a "mt3" ergo keycap set.

Thanks!

**Comment by toniz4** [comment]
And regarding the Issue with the squared scoop dish, I think I found a solution, you need to rotate the dish by the top tilt, like this:

```scad
rotate([$top_tilt,0,0]) translate([0,0,-$total_depth])shape_slice(1,0,0);
```

**Comment by toniz4** [comment]
But unfortunately it doesn't work for double sculpted keys

**Comment by jwhendy** [comment]
@toniz4 is this the "lip" you're referencing?
image(4)

I haven't looked at @mrebersv 's latest, but got him measurements using a very accurate depth mitotuyo depth guage with keys on a granite measurement stone. This was right before my wife and I had a baby and I haven't come back to this. I also have key measurements for each key shape. I also thought checking SCAD output vs. that public STL for r0 would be a way to fine tune/verify. Essentially, bring them both into CAD and align to check for mismatched geometry.

**Comment by toniz4** [comment]
@jwhendy Indeed it is, It make the edge of the dish less harsh.

**Comment by mrebersv** [comment]
Thanks for all the work and info on this!  I never got around to fixing the
pull request and doing a new one.  I'll try to squeeze time in this
weekend, though my FIL is in town and I may be rather busy.  I'll get the
changes we know we can make in, and then do a PR for that.  Then, any
additional modifications can be a PR from anyone.

**Comment by rsheldiii** [comment]
if you don't mind @mrebersv I can take it from here - I want these changes in master. I'm going to merge into a prepared branch, do the modifications, then merge into master from that branch

**Pull request merged**
